steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/notification-repo/notification-service', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/notification-repo/notification-service']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'notification-service',
      '--image=us-central1-docker.pkg.dev/$PROJECT_ID/notification-repo/notification-service',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port=50052',
      '--use-http2'
    ]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/notification-repo/notification-service

options:
  logging: CLOUD_LOGGING_ONLY
